Improved fixture and test naming scheme
jjotero/reframe pull request #3
Opened 2021-09-30 20:20 UTC by vkarak

This is along my proposal in #1794.

2021-10-01 07:44 UTC, victorusu requested changes
@vkarak, I liked it. Now, we are using Fortran class syntax (`%`) to describe the class names, right? `ClassName%prefix.parameter_name=parameter_val'`. 😉

2021-10-01 07:44 UTC, victorusu commented on reframe/core/pipeline.py
> +                self.name = type(self).basename(self.variant_num)
I am see the use of `basename` using `variant_num`... When are we using it with `compress_params` and `prefix`?

2021-10-01 07:44 UTC, victorusu commented on reframe/core/meta.py
> +                 compress_params=False, prefix=''):
I think that `compress_params` are not being used in this function... Do we need it?

2021-10-01 13:20 UTC, jjotero commented
These changes in the naming scheme are disruptive and will break tests. If you look at the name produced by the `fullname` method, the test name for a parameterized test without fixtures remains unchanged with respect to previous versions. However, the name produced by `basename` introduces a new notation and may break existing tests if these tests expected the old naming scheme for chaining dependencies and so on.

My second point is that this naming scheme does not solve the problem when the number of parameters is large. Whether you put underscores or `%` doesn't make much difference if you have a large number of parameters, or if some of your parameters are lists, dictionaries, or other structure that would make the name very long. My intention with the `fullname` method is that we eventually move to use `compress_params=True` always, which means that the name complexity will always be _O(1)_ with respect the parameter space (whereas this proposed method is still _O(n)_). With `compress_params=True`, the test would only have the variant id appended to the name, but the user can still query which are the parameter values in that variant through the `get_variant_info` classmethod.

2021-10-04 12:40 UTC, vkarak commented
As we discussed today we will use that as a human-readable version of the name, which we could merge later or apply it in a different way when we are listing the tests. We will go with the compressed naming convention, such as `MyTest@<variant_num>` for parametrised tests (normally or through fixtures) and `Fixture@<variant_num>~<fixt_hash>`. The `fixt_hash` captures the scope of the fixture. As @jjotero proposed, the default naming scheme for tests should not change, but we should introduce a configuration parameter to control this, such `use_legacy_naming_scheme`, whose default we'll toggle to true, as soon as we move to 4.0.

2022-09-29 21:53 UTC, closed without merging